-- Canonical LLM playstyle: Brawler.
-- Generated by Claude (2026-06-25) via LLM pipeline: strategy text -> ChatGPT -> config.
-- PRIMARY CONFIG (Radiant side) -- mirror match vs canonical_farmer (identical dials).
--
-- Mirror test (2026-06-26): both sides run identical Brawler config to stress-test fight
-- engine symmetry. Winner decided by rune luck, HP trade execution, and ability timing.
-- Expected: first blood 5-7 min, match under 12 min, kill-based win condition.
--
-- Do NOT modify this file -- owned by Claude, not Codex.

return {
	dials = {
		harass_desire     = 0.90,
		farm_focus        = 0.15,
		forwardness       = 0.78,
		retreat_caution   = 0.35,
		rune_control      = 0.85,
		execute_threshold = 0.42,
		ability_aggro     = 0.65,
		gank_desire       = 0.90,
		push_desire       = 0.30,
		defend_desire     = 0.25,
		ward_desire       = 0.50,
		roshan_desire     = 0.50,
	},
	item_build = {
		npc_dota_hero_nevermore = {
			"item_tango",
			"item_double_branches",
			"item_faerie_fire",
			"item_enchanted_mango",
			"item_enchanted_mango",
			"item_bottle",
			"item_magic_wand",
			"item_power_treads",
			"item_lifesteal",
			"item_dragon_lance",
			"item_lesser_crit",
			"item_black_king_bar",
			"item_orchid",
			"item_bloodthorn",
			"item_greater_crit",
			"item_hurricane_pike",
			"item_aghanims_shard",
			"item_satanic",
			"item_moon_shard",
			"item_travel_boots_2",
			"item_ultimate_scepter_2",
		},
	},
	rules = {
		respawn_behavior    = "tp_to_lane",
		pregame_behavior    = "aggressive_mid",
		dive_policy         = "finish_only",
		low_hp_behavior     = "regen_lane",
		healing_style       = "active",
		ability_usage       = "aggressive",
		creep_wave_priority = "last_hit_only",
		hero_priority       = "always",
		deny_policy         = "default",
	},
	skill_build = { npc_dota_hero_nevermore = {1,5,1,5,1,6,1,5,5,4,6,4,4,4,6} },
}
