-- Canonical LLM playstyle: Farmer.
-- Generated by Claude (2026-06-25) via LLM pipeline: strategy text -> ChatGPT -> config.
-- PRIMARY CONFIG FOR THIS MATCH (Dire side) -- replaces canonical_ganker.
--
-- Why Farmer is the primary for this run:
-- We are testing the Brawler vs Farmer contrast generated by the updated LLM system prompt (v4).
-- Farmer prioritizes last-hits and pushes the creep wave to force tower damage. Does not fight
-- unless it has a clear advantage. Waits near own T1 before first creep wave (no pregame duel).
-- rune_control=0.85 compensates for the deep push position (coherence rule #6:
--   cwp="push" + push_desire=0.78 -> rune_control must be >=0.80).
-- Compared to canonical_ganker:
--   harass 0.35 vs 0.85, farm_focus 0.80 vs 0.20, pregame_behavior=safe_tower vs aggressive_mid,
--   ability_usage=default vs aggressive, hero_priority=default vs always.
-- Expected: high CS count, tower damage win condition, fewer kills.
--
-- Do NOT modify this file -- owned by Claude, not Codex.

return {
	dials = {
		harass_desire     = 0.35,
		farm_focus        = 0.80,
		forwardness       = 0.55,
		retreat_caution   = 0.50,
		rune_control      = 0.85,
		execute_threshold = 0.48,
		ability_aggro     = 0.55,
		gank_desire       = 0.35,
		push_desire       = 0.78,
		defend_desire     = 0.55,
		ward_desire       = 0.50,
		roshan_desire     = 0.50,
	},
	item_build = {
		npc_dota_hero_nevermore = {
			"item_tango",
			"item_double_branches",
			"item_faerie_fire",
			"item_enchanted_mango",
			"item_enchanted_mango",
			"item_bottle",
			"item_magic_wand",
			"item_power_treads",
			"item_lifesteal",
			"item_dragon_lance",
			"item_lesser_crit",
			"item_black_king_bar",
			"item_orchid",
			"item_bloodthorn",
			"item_greater_crit",
			"item_hurricane_pike",
			"item_aghanims_shard",
			"item_satanic",
			"item_moon_shard",
			"item_travel_boots_2",
			"item_ultimate_scepter_2",
		},
	},
	rules = {
		respawn_behavior    = "tp_to_lane",
		pregame_behavior    = "safe_tower",
		dive_policy         = "finish_only",
		low_hp_behavior     = "regen_lane",
		healing_style       = "active",
		ability_usage       = "default",
		creep_wave_priority = "push",
		hero_priority       = "default",
		deny_policy         = "default",
	},
	skill_build = { npc_dota_hero_nevermore = {1,5,1,5,1,6,1,5,5,4,6,4,4,4,6} },
}
