@echo off
setlocal EnableExtensions

:: AIBattle deploy script.
:: Profiles:
::   code       default; engine + bot code only
::   playstyle  canonical presets + live bindings
::   all        code + playstyle, never general.lua
::   general    explicit lobby/general sync
::   check      print the full copy plan without writing

set "DEV=%~dp0..\bots"
set "DOTA=C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\scripts\vscripts\bots"
set "PROFILE=%~1"
if "%PROFILE%"=="" set "PROFILE=code"

set "DO_CODE=0"
set "DO_PLAYSTYLE=0"
set "DO_GENERAL=0"
set "DRY_RUN=0"

if /I "%PROFILE%"=="code" set "DO_CODE=1"
if /I "%PROFILE%"=="playstyle" set "DO_PLAYSTYLE=1"
if /I "%PROFILE%"=="all" (
	set "DO_CODE=1"
	set "DO_PLAYSTYLE=1"
)
if /I "%PROFILE%"=="general" set "DO_GENERAL=1"
if /I "%PROFILE%"=="check" (
	set "DO_CODE=1"
	set "DO_PLAYSTYLE=1"
	set "DO_GENERAL=1"
	set "DRY_RUN=1"
)

if "%DO_CODE%%DO_PLAYSTYLE%%DO_GENERAL%%DRY_RUN%"=="0000" (
	echo Usage: tools\deploy.bat [code^|playstyle^|all^|general^|check]
	echo.
	echo code is the default. general.lua is explicit only.
	exit /b 2
)

echo === AIBattle Deploy ===
echo PROFILE: %PROFILE%
echo FROM:    %DEV%
echo TO:      %DOTA%
if "%DRY_RUN%"=="1" echo MODE:    dry run
echo.

if "%DO_CODE%"=="1" (
	echo -- code --
	call :copyfile "FunLib\aibattle_engine.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_intents.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_item_policy.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_constants.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_context.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_build.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_style.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_runes.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_survive.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_creeps.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_safety.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_recovery.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_combat.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_tempo.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_arbiter.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_policy.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_duel.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_siege.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_survival.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_laning_trade.lua" || exit /b 1
	call :copyfile "FunLib\aibattle_utils.lua" || exit /b 1
	call :copyfile "FunLib\jmz_func.lua" || exit /b 1
	call :deletefile "FunLib\aibattle_laning_intents.lua" || exit /b 1
	call :copyfile "ability_item_usage_generic.lua" || exit /b 1
	call :copyfile "item_purchase_generic.lua" || exit /b 1
	call :copyfile "mode_laning_generic.lua" || exit /b 1
	call :copyfile "mode_roam_generic.lua" || exit /b 1
	call :copyfile "mode_retreat_generic.lua" || exit /b 1
	call :copyfile "FretBots\SettingsDefault.lua" || exit /b 1
	call :writebuild || exit /b 1
	echo.
)

if "%DO_PLAYSTYLE%"=="1" (
	echo -- playstyle --
	call :copyfile "Customize\canonical_brawler.lua" || exit /b 1
	call :copyfile "Customize\canonical_farmer.lua" || exit /b 1
	call :copyfile "Customize\canonical_pusher.lua" || exit /b 1
	call :copyfile "Customize\canonical_ganker.lua" || exit /b 1
	call :copyfile "Customize\playstyle_radiant.lua" || exit /b 1
	call :copyfile "Customize\playstyle_dire.lua" || exit /b 1
	echo.
)

if "%DO_GENERAL%"=="1" (
	echo -- general --
	call :copyfile "Customize\general.lua" || exit /b 1
	echo.
)

echo === Done. Restart lobby to pick up changes. ===
exit /b 0

:copyfile
if "%DRY_RUN%"=="1" (
	echo [PLAN] %~1
	exit /b 0
)
copy /Y "%DEV%\%~1" "%DOTA%\%~1" >nul
if errorlevel 1 (
	echo [ERR] %~1
	exit /b 1
)
echo [OK] %~1
exit /b 0

:deletefile
if "%DRY_RUN%"=="1" (
	echo [PLAN-DEL] %~1
	exit /b 0
)
if exist "%DOTA%\%~1" (
	del /F /Q "%DOTA%\%~1" >nul
	if errorlevel 1 (
		echo [ERR-DEL] %~1
		exit /b 1
	)
	echo [DEL] %~1
)
exit /b 0

:writebuild
if "%DRY_RUN%"=="1" (
	echo [PLAN] FunLib\aibattle_build.lua ^(live git sha^)
	exit /b 0
)
for /f %%G in ('git -C "%~dp0.." rev-parse --short HEAD 2^>nul') do set "AIB_GIT_SHA=%%G"
if "%AIB_GIT_SHA%"=="" set "AIB_GIT_SHA=unknown"
(
	echo -- Generated by tools\deploy.bat. Do not edit in live Dota folder.
	echo return {
	echo 	sha = "%AIB_GIT_SHA%",
	echo }
) > "%DOTA%\FunLib\aibattle_build.lua"
echo [OK] FunLib\aibattle_build.lua ^(sha %AIB_GIT_SHA%^)
exit /b 0
